### ISSUE TITLE
Updating peer dependency to React v. 18

### ISSUE THREAD

**Issue by haase1020** [Aljullu/react-lazy-load-image-component#102]
I currently use this package in my project, and would like to update my code to React v. 18 but I get a warning that there is an incorrect peer dependency. Is is possible to update this package to support React v.18? I am more than happy to help in any way I can.

**Comment by Aljullu** [comment]
Hi there @haase1020, that was done in #100. Can you check if you have the latest version installed (1.5.4)?

**Comment by haase1020** [comment]
Great! Thank you~
