### ISSUE TITLE
.blur and TailWind's  .blur duplicate name

### ISSUE THREAD

**Issue by xxxxue** [Aljullu/react-lazy-load-image-component#111]
**Bug description**

react-lazy-load-image-component 's `.blur` and TailWind's `.blur`  duplicate name

**To Reproduce**

- `effect='blur'`
- Add  `important: true`  in `tailwind.config.cjs`  
- The image is always blurred

[important Docs](https://www.tailwindcss.cn/docs/configuration#important)
[disabling blur](https://www.tailwindcss.cn/docs/blur#disabling)

tailwind.config.cjs
```js
module.exports = {
  content: ["./src/**/*.tsx"],
  theme: {
    extend: {},
  },
  plugins: [],

  // add '!important'
  important: true,

  corePlugins: {  
    preflight: false,   
    // blur:false
  },
};
```

**Expected behavior**

Compatible with tailwind's `important=true`

**Screenshots**
https://github.com/Aljullu/react-lazy-load-image-component/blob/470e2191360c0ffc25dfc2d4db4a8b97ff28bba4/src/effects/blur.css#L14

![image](https://user-images.githubusercontent.com/32764266/187652936-15e1cd8d-917f-4178-ac74-7bd50ff04d6a.png)

**Technical details:**
- Package version :  `1.5.5`
- Server Side Rendering?   `No`
- Device: `Desktop`
- Operating System : `Windows 11`
- Browser : `Chrome 104`

**Comment by cbonaco1** [comment]
Unfortunately this doesn't seem like something which can be solved by `react-lazy-load-image-component` but just a downside to using `!important`. I would recommend instead either not using `important` at all in your Tailwind config, or prefixing classes with `!` (to mark them as important) on an as-needed basis.
