### ISSUE TITLE
Lazy load isn't working?

### ISSUE THREAD

**Issue by monolithed** [Aljullu/react-lazy-load-image-component#124]
When I use tabs, the first one displays with a placeholder, but the others do not. Is there a way to add a placeholder for images that are currently hidden?
I've tried using `trackWindowScroll`, but it doesn't have any effect. When I switch to another tab, the placeholder is no longer there, even though the image hasn't loaded yet.

<img width="972" alt="Screenshot 2023-09-01 at 16 40 29" src="https://github.com/Aljullu/react-lazy-load-image-component/assets/803674/62d98d92-4353-46e5-a048-84a16ea7ed4b">

<img width="981" alt="Screenshot 2023-09-01 at 16 38 15" src="https://github.com/Aljullu/react-lazy-load-image-component/assets/803674/ab13261d-d56b-4beb-8d15-34de2f255a40">

**Comment by flyingcodestudio** [comment]
Thanks for reaching out to us, @monolithed. In the scenario you shared, it shouldn't be needed to lazy load the images, as they will only be loaded by the browser once the user activates the relevant tab. Does it make sense?

So, in your specific situation, we recommend not using React Lazy Load Image Component as it doesn't seem to be needed. We will go ahead and close this issue, but please feel free to reopen it if you believe the resolution is not appropriate.

**Comment by monolithed** [comment]
@flyingcodestudio I disagree because it works out of the box in NextJS

**Comment by monolithed** [comment]
@flyingcodestudio, This component isn't tied to any specific system, unlike NextJS, and its purpose is to handle such scenarios. By closing the ticket, you're not offering any alternatives. So, if I need a blur effect on tabs, am I expected to create my own component? 
Why was NextJS able to implement this out of the box?
