### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by AFCMS** [Aljullu/react-lazy-load-image-component#134]
React 19 just released, and I get a peer warning when installing. Everything seems to work fine in my project, so it may just be a matter of adding the version to the supported ones.

https://github.com/Aljullu/react-lazy-load-image-component/blob/75d69bed8560baf242dbff22e9c17a93998abc09/package.json#L7

**Comment by Aljullu** [comment]
Thanks for reporting this, @AFCMS! @gadingnst fixed it in #135. :slightly_smiling_face: 

I released a new version of the package, 1.6.3. Please let me know if you encounter any issues with it.
