### ISSUE TITLE
horizontal scroll not support 

### ISSUE THREAD

**Issue by JackZhang1988** [Aljullu/react-lazy-load-image-component#14]
i have a horizontal list images and I would like to apply lazyloading for items in those list too.

**Comment by Aljullu** [comment]
Hi @JackZhang1988, thanks for trying `react-lazy-load-image-component`!

The package supports lazy loading images or other components with horizontal scroll. Could you please detail a little bit more your problem to help me diagnose it? Take into account `react-lazy-load-image-component` doesn't track scroll inside container elements (like `overflow: scroll` or similar elements), only to the `<body>`. That might be the issue that is affecting you. 

I updated the demo which you can find [here](https://www.albertjuhe.com/react-lazy-load-image-component/) ([see code](https://github.com/Aljullu/react-lazy-load-image-component-demo)) to allow showing the images as an horizontal list, maybe you could use that one as a reference for your implementation.

**Comment by Aljullu** [comment]
Closing it for now since this issue has been inactive for a while.

**Comment by vitkarpov** [comment]
@Aljullu hey there, thanks for this library! 👍

I'm observing kind of the same problem. I have a horizontal container. On some screens, two items fit completely and one of them fits only half of the screen. That last item doesn't load.

Have you seen that behavior?

**Comment by wenlittleoil** [comment]
I encountered similar problems in swiper, the image inside the last swiper item doesn't load completely.
