### ISSUE TITLE
Default placeholder raise a warning

### ISSUE THREAD

**Issue by renodesper** [Aljullu/react-lazy-load-image-component#15]
Hi, it looks like the default placeholder raise a warning. Is there anything that I can do to somehow fix it?

This is the implementation that I did:

```javascript
const ImagePoster = props => (
  <MovieGalleryContent placeholderSrc={props.placeholder}>
    <LazyLoadImage
      src={props.src}
      style={{ width: '100%', height: '100%' }}
      onError={e => {
        e.target.onerror = null;
        e.target.src = '/static/img/clapperboard.svg';
      }}
      delayTime="0"
    />
  </MovieGalleryContent>
);
```

This is the warning that I got:
`Expected server HTML to contain a matching <span> in <div>.`

**Comment by Aljullu** [comment]
@renodesper thanks for raising an issue. Unfortunately I couldn't reproduce it, could you give me more details about which other packages are you using or, ideally, submit an example repo to GitHub or somewhere else so I can download it and reproduce the issue?

**Comment by renodesper** [comment]
Hi, sorry for the late reply. Unfortunately, we ended up using another library since we need to finish it fast and also need SSR functionality. I will just close the issue for now.
