### ISSUE TITLE
Got error on production preact-cli build undefined index

### ISSUE THREAD

**Issue by azulkipli** [Aljullu/react-lazy-load-image-component#2]
![react-lazy-load-image-component](https://user-images.githubusercontent.com/8231792/38409625-51337518-39ac-11e8-945e-0481299bf48a.jpg)
```
webpack://../node_modules/react-lazy-load-image-component/build/index.js
```
GET https://preactstarter.netlify.com/undefined 404 ()

**Comment by Aljullu** [comment]
Hi @azulkipli can you write some steps to reproduce it? I don't have experience with `preact-cli` and it's hard to diagnose the problem without any more details.

**Comment by azulkipli** [comment]
Hi, you can try follow 
https://github.com/developit/preact-cli
quick guide
or just clone https://github.com/azulkipli/preactstarter.git
checkout to branch: spectre
```npm install```
then ```preact build --no-prerender```

**Comment by Aljullu** [comment]
@azulkipli thank you for your report, it should be fixed now!

It seems there was an issue in the way the components were exported and `preact-cli`.

I just published a new version to npm, so running `npm update` should fix the bug. Let me know if the problem appears again.

**Comment by azulkipli** [comment]
This problem still exist
