### ISSUE TITLE
Error window is not defined in server side rendering

### ISSUE THREAD

**Issue by MekMed** [Aljullu/react-lazy-load-image-component#21]
**Bug description**
Actually, when the component is used on server side rendering, it generate a "window is not defined" error.

**Expected behavior**
A test for "window" can be added in order to avoid access to this variable if not defined.
To be added in both LazyLoadImage and trackWindowScroll

**Technical details:**
- Server Side Rendering? Yes
- Device Desktop/Smartphone
- Operating System All
- Browser All

Thx,

**Comment by Aljullu** [comment]
Hi @MekMed, thanks for trying `react-lazy-load-image-component` and filling a bug.

I just released a new version which doesn't address this issue specifically but might solve it. Could you test it again with the latest version (`1.2.0`)? Thank you!

**Comment by daveyheuser** [comment]
I have the same issue (Netlify fails to build the site because of this error). FWIW I'm using this in combination with Gatsby.

**Comment by ashbrowning** [comment]
I've also been getting the same thing. Filled #26 which fixes this issue for me.

**Comment by MekMed** [comment]
@Aljullu @ashbrowning thx for your work and time.

**Comment by Aljullu** [comment]
I just uploaded the version 1.2.1 to npm with this fix and a fix for #19.

@ashbrowning thanks again for fixing those two issues. :tada:
