### ISSUE TITLE
Forgotten `console.log('render');` in npm build 

### ISSUE THREAD

**Issue by bu1ka** [Aljullu/react-lazy-load-image-component#29]
**Bug description**
When package installed via npm it logging in console `render`.
It's placed in 
`react-lazy-load-image-component/src/components/LazyLoadComponent.jsx:    console.log('render');`

**To Reproduce**
`npm i react-lazy-load-image-component@1.3.0` 
or just open console in devtools on https://www.albertjuhe.com/react-lazy-load-image-component/

**Expected behavior**
No debug code in build

**Screenshots**
![image](https://user-images.githubusercontent.com/2262052/51106458-e30d2e00-17fc-11e9-85fe-bfe481bad03b.png)

**Technical details:**
- Package version 1.3.0
- Server Side Rendering? No
- Device [Desktop/Smartphone]: Any
- Operating System [e.g. Windows, Mac OS, GNU/Linux]: Any
- Browser [e.g. Firefox, Chrome, Safari]: Any

**Comment by Aljullu** [comment]
My bad :man_facepalming: . Should be fixed now in version `1.3.2`: https://github.com/Aljullu/react-lazy-load-image-component/releases/tag/1.3.2.

Thanks @bu1ka for catching this!

**Comment by bu1ka** [comment]
Thank you for a quick fix ⚡️
