### ISSUE TITLE
delaytime and delaymethod is not working

### ISSUE THREAD

**Issue by ninjasparda** [Aljullu/react-lazy-load-image-component#35]
I tried to use the component like this
 <LazyLoadImage
            delayTime={10000}
            src={'/photo.jpg'} />}

but it's not working, and when I am digging into your source code, I found out LazyLoadImage pass the prop delayTime and delayMethod to LazyLoadComponent but then they are not in use in LazyLoadComponent, 

could you let me know this is a bug or this feature never works?

**Comment by ninjasparda** [comment]
In the end of day I am using another library to achieve this due to lack of support for this library
https://github.com/twobin/react-lazyload

**Comment by Aljullu** [comment]
Right, there seems to be a bug here. Thanks for reporting @ninjasparda!

**Comment by Aljullu** [comment]
I released a beta version which includes a fix for this. Feel free to test it and provide feedback or report bugs if you find them.

You can install it with:
```sh
npm i --save react-lazy-load-image-component@1.4.0beta.0
```
