### ISSUE TITLE
Is it possible to use srcset?

### ISSUE THREAD

**Issue by ZLevine** [Aljullu/react-lazy-load-image-component#37]
Using the `img` tag's `srcset` attribute can improve performance massively by selectively loading different images for different devices based on resolution and pixel density. Does this library support `srcSet` lazy-loading, similar to `lazysizes`? Thanks!

**Comment by Aljullu** [comment]
@ZLevine yes, you can pass all attributes accepted by `<img>` elements to `<LazyLoadImage />`, that includes the `srcset` attribute.

**Comment by pixelfreak** [comment]
May I recommend adding this to the documentation? I can do that if you'd like and if you give me a quick instructions :)

**Comment by Aljullu** [comment]
Hi @pixelfreak! Sure, this would be a good addition to the documentation.

This is more or less explained in the last row of the props table:

https://github.com/Aljullu/react-lazy-load-image-component#props

_Any other image attribute_ includes `srcset` as well as other `img` attributes like `alt`, `src`, etc. I agree it might be good specifying them to make it more clear.

You can read the [GitHub Docs on how to create a Pull Request](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/creating-an-issue-or-pull-request#creating-a-new-pull-request). You will need to modify the `README.md` file, find the _Any other image attribute_ strings and replace them with something like _Any other image attribute (`alt`, `src`, `srcset`...)_.

Notice you will need to modify it in [this table](https://github.com/Aljullu/react-lazy-load-image-component#props-2) too.

Thank you in advance!
