### ISSUE TITLE
Is it possible to use Passive Event Listeners to improve performance?

### ISSUE THREAD

**Issue by ARDde** [Aljullu/react-lazy-load-image-component#38]
In trackWindowScroll.js you are using normal event listeners. If you use Passive Event Listeners you get a better performance on scrolling:

https://developers.google.com/web/updates/2016/06/passive-event-listeners

All you have to do is to add a third parameter (true) to the listener.

Example:
window.addEventListener('resize', this.delayedScroll, true);

Best regards
Marcel

**Comment by Aljullu** [comment]
Hi @ARDde, this sounds like a good addition. I guess you really meant this, right?
```ES6
 window.addEventListener('resize', this.delayedScroll, { passive: true });
```

I added this setting in 1fb0c29bc762a1c55777b08030691f2fb88b918d and it should be included in the next release.

Thank you for the suggestion!

**Comment by Aljullu** [comment]
I released a beta version which includes this improvement. Feel free to test it and provide feedback or report bugs if you find them.

You can install it with:
```sh
npm i --save react-lazy-load-image-component@1.4.0beta.0
```
