### ISSUE TITLE
lazyLoad doesn't work,

### ISSUE THREAD

**Issue by LastStranger** [Aljullu/react-lazy-load-image-component#39]
**Bug description**
Write a clear and concise description of what the bug is.
all the images loaded in the same time;

**To Reproduce**
Paste the code that is producing the issue
```js
import React from "react";
import { LazyLoadImage } from 'react-lazy-load-image-component';
import uuid from 'uuid/v4';
import 'react-lazy-load-image-component/src/effects/blur.css';

import styles from './lazyImages.less';
import images from "./images";

const LazyImage = () => {
	return (
		<div className={styles.lazyImages}>
			{
				images().map((item) => {
					return <LazyLoadImage effect="blur" src={item.src} key={uuid()}/>
				})
			}
		</div>
	);
};

export default LazyImage;
```
```js
const images = () => {
	return [
		{
			src: '/app/images/lazyImages/a.jpg'
	    },
		{
			src: '/app/images/lazyImages/b.jpg'
		},
		{
			src: '/app/images/lazyImages/c.jpg'
		},
		{
			src: '/app/images/lazyImages/d.jpg'
		},
		{
			src: '/app/images/lazyImages/e.jpg'
		},
	]
};
export default images;
```

```less
.lazyImages{
    img{
        width: 100vw;
    }
}
```
![image](https://user-images.githubusercontent.com/29811304/59490534-88fdbb00-8eb7-11e9-93de-cd873eca4261.png)
#### I havn't scroll yet, all the images loaded already;

List any other actions needed to reproduce the issue:
- Scroll to '...'.
- Click on '...'.

Link to a repo where this issue can be reproduced if available:

**Expected behavior**
Write a clear and concise description of what you expected to happen versus what happened.

**Screenshots**

**Technical details:**
- Package version [1.3.2]
- Server Side Rendering? [no]
- Device [desktop but mobile mode]
- Operating System [windows]
- Browser [chrome]

**Comment by Aljullu** [comment]
You probably need to set a `height` and `width` from the beginning, otherwise when the page is loaded, all images are in the viewport so all of them are loaded at once. If you hard-code the size beforehand, only the images which occupy space in the viewport will be loaded.

Hope that helps.
