### ISSUE TITLE
Support for TypeScript?

### ISSUE THREAD

**Issue by diegochavez** [Aljullu/react-lazy-load-image-component#40]
Any plans to support TypeScript I can start with the Types definitions file? :)

**Comment by diegochavez** [comment]
This is a WIP :D 👍 
``` typescript
declare module 'react-lazy-load-image-component' {
  import { Styles } from 'jss';
  import * as React from 'react';
  export const LazyLoadImage: React.FunctionComponent<{
    afterLoad?: () => any;
    beforeLoad?: () => any;
    delayMethod?: string;
    delayTime?: number;
    effect?: string;
    placeholderSrc?: string;
    threshold?: number;
    visibleByDefault?: boolean;
    wrapperClassName?: string;
    src?: string;
    width?: number;
    height?: number;
    className?: string | Styles;
  }>;
  enum DelayMethod {
    debounce = "debounce", 
    throttle = "throttle"
  };
  interface LazyComponentProps { 
    delayMethod: DelayMethod;
    delayTime: number
  };
  export const trackWindowScroll: (BaseComponent: React.ComponentType<P>) => BaseComponent<P & LazyComponentProps, S>;
  export const LazyLoadComponent: React.Component<{
    afterLoad: () => void,
    beforeLoad: () => void,
    visibleByDefault: boolean,
  }>;
  export const LazyLoadComponent: React.FunctionComponent<{}>;
};
`

**Comment by d-bo** [comment]
Also seems there is no way to include it through ```tsconfig.json``` without ejecting react-create-app.
Nice to get it as a ```npm install @types/react-lazy-load-image-component```

```
TypeScript error: Could not find a declaration file for module 
'react-lazy-load-image-component'. '/prj/node_modules/
react-lazy-load-image-component/build/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-lazy-load-image-component` if it exists or add 
a new declaration (.d.ts) file containing 
`declare module 'react-lazy-load-image-component';`  TS7016
```

**Comment by diegochavez** [comment]
ejecting? no, you only include this file in your typescript project as react-lazy-load-image-component.d.ts

**Comment by d-bo** [comment]
the path to include ?

**Comment by diegochavez** [comment]
@d-bo can be anywhere in the project but should work with a /typings directory on the root of your project Typescript pickup any .d.ts file and try to match.

@Aljullu I'll make a PR to include the d.ts in this project. 👍

**Comment by zerosym** [comment]
Thanks for the typings.  I noticed some valid image attributes such as "alt" are missing though and they should all be valid as per the bottom row of the props table in the docs.

https://github.com/Aljullu/react-lazy-load-image-component/blob/master/README.md#props

**Comment by danvk** [comment]
I've published type declarations for this package on DefinitelyTyped. You can get them via:

    npm install -D @types/react-lazy-load-image-component

The props for `LazyLoadImage` derive from `HTMLImageElement`, so everything should be there.

**Comment by Aljullu** [comment]
Closing this issue now that @danvk created the declarations in DefinitelyTyped (thank you!). I added a link in the [README file](https://github.com/Aljullu/react-lazy-load-image-component#features) so they are easy to find.
