### ISSUE TITLE
HOC doesn't track scroll position - `scrollPosition` is always `null`

### ISSUE THREAD

**Issue by ndtreviv** [Aljullu/react-lazy-load-image-component#42]
**Bug description**
I'm wrapping a component in `trackScrollPosition`, and it's adding `scrollPosition` to the component props, but it's always `null`.

**To Reproduce**
See it here: https://stackblitz.com/edit/react-x6zjfs

**Expected behavior**
I'd expect scrollPosition to update whenever the window scrolls.

**Screenshots**
N/A

**Technical details:**
- Package version: *1.3.2*
- Server Side Rendering? *No*
- Device: *Desktop*
- Operating System: *Mac OS*
- Browser: *Chrome*

**Comment by FacundoMainere** [comment]
Same here

**Comment by FacundoMainere** [comment]
i spent some time looking at the code, and it seems like, in browsers that support intersectionObserver, this HOC does nothing, and thats the intended behavior.

What version of chrome are you using? if its over 51(it's 3 years old) you have support for intersection observer.

**Comment by Aljullu** [comment]
Right, as @FacundoMainere said if your browser supports `IntersectionObserver`, the HOC doesn't pass `trackScrollPosition` down.

Would a `useIntersectionObserver` prop which allows disabling the IntersectionObserver be useful? I created a WIP PR here: #45, feel free to take a look.

**Comment by MartinKristof** [comment]
Can U merge it, pls?

**Comment by Aljullu** [comment]
I released a beta version which includes this new prop. Feel free to test it and provide feedback or report bugs if you find them.

You can install it with:
```sh
npm i --save react-lazy-load-image-component@1.4.0beta.0
```
