### ISSUE TITLE
Load Animations are not working correctly

### ISSUE THREAD

**Issue by CodingOni** [Aljullu/react-lazy-load-image-component#43]
**Bug description**
Write a clear and concise description of what the bug is.
When the component is scrolled into view and is loading the animations are not working correctly

**To Reproduce**
Paste the code that is producing the issue
```
...Add lazy load to an image with     effect="blur"
 prop and it will not work i have tried all effects
```

List any other actions needed to reproduce the issue:
- Scroll to '...'.
- Click on '...'.

Link to a repo where this issue can be reproduced if available:

**Expected behavior**
Write a clear and concise description of what you expected to happen versus what happened.

**Screenshots**

**Technical details:**
- Package version [e.g. 1.2.0]
- Server Side Rendering? [Yes/No]
- Device [Desktop/Smartphone]
- Operating System [e.g. Windows, Mac OS, GNU/Linux]
- Browser [e.g. Firefox, Chrome, Safari]

**Comment by nuhman** [comment]
I had the same issue and that's when I noticed you need to require the css file by:
`import 'react-lazy-load-image-component/src/effects/blur.css';`

**Comment by alexlpdj** [comment]
> I had the same issue and that's when I noticed you need to require the css file by:
> `import 'react-lazy-load-image-component/src/effects/blur.css';`

This made my day! thanks a lot!

**Comment by Aljullu** [comment]
I added this issue to the 'Common errors' section in the README so it's easier to discover. Will close this issue for now.
