### ISSUE TITLE
i want fullapage effect ？

### ISSUE THREAD

**Issue by 97thjingba** [Aljullu/react-lazy-load-image-component#44]
**How do I make the image fit just like the full page to fit the screen of each of my devices and just fill it up?**

[just like this ](https://ocean-artup.eu/)

**Comment by Aljullu** [comment]
You should be able to achieve this making images to be 100% height and 100% width of the viewport sizes. Take a look at `vh` and `vw` here:

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units#Dimensions

Hope that works!
