### ISSUE TITLE
Images are not downloading in chrome desktop

### ISSUE THREAD

**Issue by grkpranaykumar** [Aljullu/react-lazy-load-image-component#53]
**Bug description**
Images are not downloading after the page loads. If I zoom out size to 90% then they are getting downloaded. On 100% resolution of screen no image is downloaded on the page.
This issue is occuring only on my chrome desktop.

I used 
<LazyLoadImage src={backGroundImageLink} alt=' ' />
for lazy loading the image on the tuples

This is the original webpage on 100% resolution
![Screenshot from 2019-11-29 21-47-23](https://user-images.githubusercontent.com/14095172/69881093-f1b7e300-12f1-11ea-8e8f-3530973e3b48.png)

And this is the screen after I zoom out the screen resolution to 90%
![Screenshot from 2019-11-29 21-48-56](https://user-images.githubusercontent.com/14095172/69881181-3b083280-12f2-11ea-95c3-f83d1c8210b1.png)

**Technical details:**
- Package version [e.g. 1.3.2]
- Device [Desktop]
- Operating System [e.g.Linux(Ubuntu)]
- Browser [e.g.  Chrome 77.0.3865.90 (Official Build) ]

**Comment by gobr** [comment]
did you pass `width` and `height` attrs to the component?

**Comment by jsakas** [comment]
Also had this issue. For me it would not load a column in a grid of images. Resizing the window somehow triggered them to load. 

Adding width and height attributes fixed it, but would be nice if those were not required.

**Comment by matevosyanmko** [comment]
Adding a border somehow fixes the issue. for example  `border: 1px solid transparent `

**Comment by elamperti** [comment]
It also works if you set a `min-width` and `min-height`, I guess basically anything that forces the image bounding box to be more than 0x0. It would be very useful if it wasn't needed or if the library could add a CSS rule for it, perhaps.

**Comment by MathieuDebit** [comment]
I had the same issue with `<LazyLoadComponent />`. Fixed this way:

```js
const Placeholder = styled.div`
  min-width: 1px;
  min-height: 1px;
`;

<LazyLoadComponent placeholder={<Placeholder />}>
    <Component />
</LazyLoadComponent>
```

**Comment by Aljullu** [comment]
Unfortunately, I'm unable to reproduce. Do you happen to know:

* Is this happening in other browsers besides Chrome?
* Is this happening with `LazyLoadImage` and `LazyLoadComponent` or only one of them?
* The images which are not loading are the ones above the fold, below the fold or all of them?
* Do you have a repo or a live site where this issue is reproducible?

Thanks in advance!
