### ISSUE TITLE
How to apply loader gif before loading of the image

### ISSUE THREAD

**Issue by prithesh990** [Aljullu/react-lazy-load-image-component#57]
**Bug description**
I have tried to put html elements/ img tag in dom before loading of the image using ur props in lazylading image component but its not working only console works nothing else

**To Reproduce**
const MyImage = (props) => {
    const url = "https://i.giphy.com/media/xTk9ZvMnbIiIew7IpW/giphy.webp"
    const spinner = () => {

        
        console.log('loading')
        return (
            <img src={url} alt="spinner" />
    }
    const afterloading = () => {
        console.log('after loading')
    }

    return (<div>
        <LazyLoadImage
            alt={props.alt}
            height={props.height}
            src={props.src} // use normal <img> attributes as props
            width={props.width}
            effect="blur"
            beforeLoad={spinner}
            afterLoad={afterloading}
            threshold="100" />
        <span>{props.keys}</span>
    </div>
    );
}
```
...
```

List any other actions needed to reproduce the issue:
- Scroll to '...'.
- Click on '...'.

Link to a repo where this issue can be reproduced if available:

**Expected behavior**
Write a clear and concise description of what you expected to happen versus what happened.

**Screenshots**

**Technical details:**
- Package version :1.4.1
- Server Side Rendering? No
- Device Desktop
- Operating System : Windows,
- Browser  :Chrome, Safari

**Comment by webistomin** [comment]
Use `placeholderSrc` prop

**Comment by Aljullu** [comment]
As @webistomin said, you should use `placeholder` or `placeholderSrc` to render something before the image loads. `beforeLoad` should be used to run code right before the image loads, but you can't render components inside that function.

Hope that helps, I will close this issue since it hasn't had activity for some time now.
