### ISSUE TITLE
Do not use !important in css for animations

### ISSUE THREAD

**Issue by EliasTouil** [Aljullu/react-lazy-load-image-component#65]
**Bug description**
!important overrides my custom styles on container element

**To Reproduce**

```
.container {
background-image: url(https://someimgae.com);
}
```

List any other actions needed to reproduce the issue:
Add a background-image attribute to the container class

**Expected behavior**
I can override any style in this component

**Comment by Aljullu** [comment]
Hi @EliasTouil, are you referring to the `opacity` effect? I created a PR to remove that CSS rule, which I think should be safe: #72.

**Comment by EliasTouil** [comment]
@Aljullu yes ! 
I'll close this issue, thank you for the PR

**Comment by Aljullu** [comment]
This is already fixed in the beta version you can get from:
```npm
$ npm i react-lazy-load-image-component@1.5.0-beta.0
```
Feel free to test and report any issues. :slightly_smiling_face:
