### ISSUE TITLE
Re-Render causes effect to replay

### ISSUE THREAD

**Issue by popmatik** [Aljullu/react-lazy-load-image-component#68]
Hi there, 

I've noticed when the state is updated it causes a re-render of all child elements. If that is a LazyLoad image with an effect of opacity on it the CSS transition is re-triggered. 

Is there any way to prevent this? 

Thanks!

**Comment by popmatik** [comment]
I figured this one out with a shouldComponentUpdate call on the parent component. Thanks.

**Comment by darcy-vitacca** [comment]
Could you post a snippet of your code please?

**Comment by darcy-vitacca** [comment]
I had this issue also and it related to incorrect key assignment hopefully this helps someone.
