### ISSUE TITLE
Lazy load image on `src` change

### ISSUE THREAD

**Issue by pszalko** [Aljullu/react-lazy-load-image-component#69]
**Bug description**
I'm not sure if it's a bug or missing feature.
I would expect to see placeholder again after changing the `src` prop in `<LazyLoadImage />`

**To Reproduce**
I use `this.props.imageUrl` to get an url from parent component.
`this.props.imageUrl` changes on an external event. I think it does not matter how. 

The code for reproducing the issue is:
```
<LazyLoadImage
                        src={this.props.imageUrl}
                        effect="opacity"
                        placeholder={<div className="loader" />}
                    />
```

Actions to reproduce:
* after loading the image, change `this.props.imageUrl` to other URL.
The image is loaded, but placeholder nor the `beforeLoad` and `afterLoad` functions are not called.

**Expected behavior**
I would expect to have:
1. Placeholder displayed when image is loading again after changed `src` property.
2. Functions `beforeLoad` and `afterLoad` called when `src` property was changed.

**Technical details:**
- Package version [1.4.3]
- Server Side Rendering? [No]
- Device [Desktop]
- Operating System [Mac OS]
- Browser [Chrome]

**Comment by Aljullu** [comment]
Yeah... the way it works will not show the placeholder again after the first image has been loaded... One thing you could try is to pass a `key` prop that changes with the `src`, something like this:

```JSX
<LazyLoadImage
  key={this.props.imageUrl}
  src={this.props.imageUrl}
  effect="opacity"
  placeholder={<div className="loader" />}
/>
```

Changing the `key` prop will make React think it's a different component so it will get remounted. Not sure if it will work, but might be worth trying.

**Comment by henrikgundersen** [comment]
Thanks @Aljullu! 🎉 
Adding unique key like `key={this.props.imageUrl}` works fine.
