### ISSUE TITLE
Would you mind to share the code of Live Demo?

### ISSUE THREAD

**Issue by hejiaji** [Aljullu/react-lazy-load-image-component#9]
It would be helpful.

**Comment by Aljullu** [comment]
There you go: :slightly_smiling_face: 

https://github.com/Aljullu/react-lazy-load-image-component-demo

I have to say the code is quite messy, but it might be helpful to see how it uses `react-lazy-load-image-component`.

In my profile, you can find a couple of other apps that also use it:

- https://github.com/Aljullu/weather-app
- https://github.com/Aljullu/react-flickr-gallery

**Comment by hejiaji** [comment]
Thanks mate!
