### ISSUE TITLE
Do I need Lazy Load Image Component for Next.js?

### ISSUE THREAD

**Issue by sohamsshah** [Aljullu/react-lazy-load-image-component#91]
In Next.js Image Component from `next/image` gives the same functionality. Does this library has better performance over the Next built-in Image lib?

**Comment by Aljullu** [comment]
I'm not very familiar with `next/image` but looking at its documentation, it seems to be using the [native lazy loading from browsers](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading).

Based on that, I would say the advantages of `react-lazy-load-image-component` are:

* Placeholder integrated by default: you can render a smaller image or a component while the big image is downloading.
* Integrated CSS effects ready to use.
* Better control of the lazy loading behavior via `delayMethod`, `delayTime` and `threshold` props.
* Events like `afterLoad`, `beforeLoad`, etc.
* Broader browser support.

If you don't need any of these, I think you are good using the native `lazy` attribute supported by browsers in images.

I will close this issue for now given that it's not directly actionable. But feel free to answer if you have any other questions.

**Comment by sohamsshah** [comment]
Thank you so much for clarifying! Will consider this. Yes, React Lazy Load Component has great support for blur effect loading and placeholder integrations.
